---
services:
  mongo:
    image: mongo:6 
    container_name: 100freelancers
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: freelance
      MONGO_INITDB_ROOT_PASSWORD: freelance
      
